### ISSUE TITLE
无法下载magnet

### ISSUE THREAD

**Issue by Yansre** [hanjm/file_download_proxy#4]
magnet链接：magnet:?xt=urn:btih:0D3DEBBB422CD90C8C236B6DDB530C75517F75FE
报错信息：
magnet:?xt=urn:btih:0D3DEBBB422CD90C8C236B6DDB530C75517F75FEaria2 error:InfoHash 0d3debbb422cd90c8c236b6ddb530c75517f75fe is already registered. source_url:stat download/txturnbtih0D3DEBBB422CD90C8C236B6DDB530C75517F75FE-1504174384: no such file or directory

**Comment by hanjm** [comment]
magnet下载时有两个过程, 先下载metadeta, 此时不会创建文件, 然后再下载相关文件. 之前代码处理有问题, 最近重构了整个代码, 已解决此问题.
